name: Docker Image Publish

on:
  schedule:
    - cron: '18 18 * * *'
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
    paths:
      - 'root/**'
      - 'Dockerfile'
      - '.dockerignore'
  
env:
  REGISTRY: docker.io
  IMAGE_NAME: xfqz86/aria2-srv


jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Action for checking out a repo
      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # Action to set up Docker Buildx
      # https://github.com/docker/setup-buildx-action
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1

      # Action to login against a Docker registry
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Action to extract metadata (tags, labels) from Git reference and GitHub events for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Action to build and push Docker images with Buildx
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6
          file: Dockerfile
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
